# Generated by Django 4.2.1 on 2023-05-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientinrecipe_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='measurement_unit',
        ),
    ]
