# Generated by Django 4.2.1 on 2023-05-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredientinrecipe_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='name',
            new_name='recipe',
        ),
    ]
