# Generated by Django 4.2.1 on 2023-05-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_name_ingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='recipe',
            new_name='name',
        ),
    ]
