# Generated by Django 4.2.1 on 2023-05-23 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipe_ingredientinrecipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='>= 1')], verbose_name='Количество'),
        ),
    ]
